// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhcceizqocpurcsqoynp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oY2NlaXpxb2NwdXJjc3FveW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODQ4MjQsImV4cCI6MjA2ODY2MDgyNH0.LAjzKulppfII_6nxQn2LuzW43NvlAT5Z1RhsdKgakRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});